### ISSUE TITLE
Token recreated: ExpiredAuthorizationException

### ISSUE THREAD

**Issue by zotona** [antonleliuk/spring-social-botFramework#18]
It seems, what token is not recreated. How to make properly recreate token?
```
in context with path [] threw exception [Request processing failed; nested exception is org.springframework.social.ExpiredAuthorizationException: The authorization has expired.] with root cause

org.springframework.social.ExpiredAuthorizationException: The authorization has expired.
        at org.springframework.social.connect.support.OAuth2Connection$ApiInvocationHandler.invoke(OAuth2Connection.java:150) ~[spring-social-core-1.1.4.RELEASE.jar!/:1.1.4.RELEASE]
        at com.sun.proxy.$Proxy100.sendToConversation(Unknown Source) ~[?:?]
        at org.springframework.social.botframework.service.impl.BotServiceImpl.reply(BotServiceImpl.java:49) ~[spring-social-botframework-core-0.0.3.jar!/:?]

```

**Comment by antonleliuk** [comment]
@zotona in current implementation no way. I thought is should do a Spring social, but it was my mistake when a create single instance of BotFramework

**Comment by antonleliuk** [comment]
Close #8 after fixing this
